{
 "title": "Windows Server Monitoring",
 "description": "Windows",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(wmi_system_system_up_time, instance)"
    }
   },
   {
    "name": "cpumode",
    "label": "cpumode",
    "query": {
     "query": "label_values(wmi_cpu_time_total, mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disks Free",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "Hard Disk Free Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}) / windows_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} * 100",
     "legendFormat": "Free {{volume}}"
    }
   ]
  },
  {
   "title": "C:\\ Space Free",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} - windows_logical_disk_free_bytes{instance=~\"$server.*\", volume=\"C:\"}) / windows_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "C:\\ - Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} "
    }
   ]
  },
  {
   "title": "HD - Used",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "Hard Disk Used Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}) / windows_logical_disk_size_bytes{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"} * 100",
     "legendFormat": "used {{volume}}"
    }
   ]
  },
  {
   "title": "C:\\ - Space used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} - windows_logical_disk_free_bytes{instance=~\"$server.*\", volume=\"C:\"}) / windows_logical_disk_size_bytes{instance=~\"$server.*\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "HOST",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$server.*\"}[1m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$server.*\"}[1m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"localhost:9182\"} - windows_os_physical_memory_free_bytes{instance=~\"localhost:9182\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"localhost:9182\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Physical Memory Free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_cs_physical_memory_bytes{instance=~\"$server.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}) / windows_cs_physical_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=~\"$server.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}) / windows_cs_physical_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$server.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"localhost:9182\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server.*\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$server.*\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Net Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(irate(windows_net_bytes_total{instance=~\"$server.*\"}[5m])) / sum(windows_net_current_bandwidth{instance=~\"$server.*\"}/8) * 100"
    }
   ]
  }
 ]
}